//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.11 at 02:01:01 PM CEST 
//


package com.megatravel.ratingservice.model;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.validation.constraints.NotNull;

@Entity
public class Komentar {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	protected Long idKomentara;
	
	@NotNull
    protected Long idSmestaja;
	
	@NotNull
    protected Long idRezervacije;
	
	@NotNull
    protected Long idKorisnika;
	
	@NotNull
    protected String komentar;
	
	@NotNull
    protected Date timestamp;
	
	@NotNull
    protected StatusKomentara status;
    
    public Komentar() {	}
    
    public Komentar(Long idKomentara, Long idSmestaja, Long idRezervacije, Long idKorisnika, String komentar, StatusKomentara statusKomentara) {
		super();
		this.idKomentara = idKomentara;
		this.idSmestaja = idSmestaja;
		this.idRezervacije = idRezervacije;
		this.idKorisnika = idKorisnika;
		this.komentar = komentar;
		this.timestamp = new Date(System.currentTimeMillis());
		this.status = statusKomentara;
	}

	public StatusKomentara getStatus() {
		return status;
	}

	public void setStatus(StatusKomentara status) {
		this.status = status;
	}

	public Date getTimestamp() {
		return timestamp;
	}

	/**
     * Gets the value of the idKomentara property.
     * 
     */
    public Long getIdKomentara() {
        return idKomentara;
    }

    /**
     * Gets the value of the idSmestaja property.
     * 
     */
    public Long getIdSmestaja() {
        return idSmestaja;
    }
    
    /**
     * Gets the value of the idRezervacije property.
     * 
     */
    public Long getIdRezervacije() {
        return idRezervacije;
    }

    /**
     * Gets the value of the idKorisnika property.
     * 
     */
    public Long getIdKorisnika() {
        return idKorisnika;
    }

    /**
     * Gets the value of the komentar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKomentar() {
        return komentar;
    }

    /**
     * Sets the value of the komentar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKomentar(String value) {
        this.komentar = value;
        this.timestamp = new Date(System.currentTimeMillis());
    }

}
