//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.01 at 10:28:48 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(
		xmlns = {@XmlNs(prefix="ns3", namespaceURI="https://megatravel.com")},
		namespace = "https://megatravel.com",
		elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
		attributeFormDefault = javax.xml.bind.annotation.XmlNsForm.UNSET
		)
package com.megatravel.agentglobalback.model;

import javax.xml.bind.annotation.XmlNs;
