//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.22 at 11:00:08 PM CEST 
//


package io.webxml.korisnikservice.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DodatneUsluge.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DodatneUsluge">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Parking"/>
 *     &lt;enumeration value="WiFi"/>
 *     &lt;enumeration value="Dorucak"/>
 *     &lt;enumeration value="Polupansion"/>
 *     &lt;enumeration value="Pansion"/>
 *     &lt;enumeration value="AllIncluded"/>
 *     &lt;enumeration value="DozvoljeniKucniLjubimci"/>
 *     &lt;enumeration value="TV"/>
 *     &lt;enumeration value="MiniKuhinjaIliKuhinja"/>
 *     &lt;enumeration value="PrivatnoKupatilo"/>
 *     &lt;enumeration value="BesplatnoOtkazivanje"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DodatneUsluge")
@XmlEnum
public enum DodatneUsluge {

    @XmlEnumValue("Parking")
    PARKING("Parking"),
    @XmlEnumValue("WiFi")
    WI_FI("WiFi"),
    @XmlEnumValue("Dorucak")
    DORUCAK("Dorucak"),
    @XmlEnumValue("Polupansion")
    POLUPANSION("Polupansion"),
    @XmlEnumValue("Pansion")
    PANSION("Pansion"),
    @XmlEnumValue("AllIncluded")
    ALL_INCLUDED("AllIncluded"),
    @XmlEnumValue("DozvoljeniKucniLjubimci")
    DOZVOLJENI_KUCNI_LJUBIMCI("DozvoljeniKucniLjubimci"),
    TV("TV"),
    @XmlEnumValue("MiniKuhinjaIliKuhinja")
    MINI_KUHINJA_ILI_KUHINJA("MiniKuhinjaIliKuhinja"),
    @XmlEnumValue("PrivatnoKupatilo")
    PRIVATNO_KUPATILO("PrivatnoKupatilo"),
    @XmlEnumValue("BesplatnoOtkazivanje")
    BESPLATNO_OTKAZIVANJE("BesplatnoOtkazivanje");
    private final String value;

    DodatneUsluge(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DodatneUsluge fromValue(String v) {
        for (DodatneUsluge c: DodatneUsluge.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
