//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.22 at 11:00:08 PM CEST 
//


package io.webxml.pretragaservice.model;

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mesto">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="datumDolaska" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="datumPolaska" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="cena" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mesto",
    "datumDolaska",
    "datumPolaska",
    "cena"
})
@XmlRootElement(name = "OsnovnaPretraga")
public class OsnovnaPretraga {

    @XmlElement(required = true)
    private String mesto;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    private Date datumDolaska;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    private Date datumPolaska;
    /*@XmlElement(required = true)
    private float cena;*/
    @XmlElement(required = true)
    private float cena;

    public OsnovnaPretraga() {

  	}
    
    public OsnovnaPretraga(String mesto, Date datumDolaska, Date datumPolaska, float cena) {
		super();
		this.mesto = mesto;
		this.datumDolaska = datumDolaska;
		this.datumPolaska = datumPolaska;
		this.cena = cena;
	}

	/**
     * Gets the value of the mesto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMesto() {
        return mesto;
    }

    /**
     * Sets the value of the mesto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMesto(String value) {
        this.mesto = value;
    }

    /**
     * Gets the value of the datumDolaska property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getDatumDolaska() {
        return datumDolaska;
    }

    /**
     * Sets the value of the datumDolaska property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setDatumDolaska(Date value) {
        this.datumDolaska = value;
    }

    /**
     * Gets the value of the datumPolaska property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getDatumPolaska() {
        return datumPolaska;
    }

    /**
     * Sets the value of the datumPolaska property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setDatumPolaska(Date value) {
        this.datumPolaska = value;
    }

    /**
     * Gets the value of the cena property.
     * 
     * @return
     *     possible object is
     *     {@link float }
     *     
     */
    public float getBrojOsoba() {
        return cena;
    }

    /**
     * Sets the value of the cena property.
     * 
     * @param value
     *     allowed object is
     *     {@link float }
     *     
     */
    public void setBrojOsoba(float value) {
        this.cena = value;
    }

}
