//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.22 at 11:00:08 PM CEST 
//


package io.webxml.pretragaservice.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idSmestaja",
    "adresa",
    "koordinate",
    "tipSmestaja",
    "kategorijaSmestaja",
    "opis",
    "maxOsoba",
    "maxDanaZaOtkazivanje",
    "cenaProlece",
    "cenaLeto",
    "cenaJesen",
    "cenaZima",
    "vlasnik",
    "listaDodatnihUsluga",
    "listaSlika"
})
@XmlRootElement(name = "Smestaj")
public class Smestaj {

    protected long idSmestaja;
    @XmlElement(required = true)
    protected String adresa;
    @XmlElement(required = true)
    protected BigDecimal latitude;
    @XmlElement(required = true)
    protected BigDecimal longitude;
    @XmlElement(required = true)
    protected TipSmestaja tipSmestaja;
    @XmlElement(required = true, defaultValue = "no star")
    private KategorijaSmestaja kategorijaSmestaja;
    @XmlElement(required = true)
    protected String opis;
    @XmlElement(required = true)
    protected int maxOsoba;
    @XmlElement(required = true)
    protected int maxDanaZaOtkazivanje;
    @XmlElement(required = true)
    protected BigDecimal cenaProlece;
    @XmlElement(required = true)
    protected BigDecimal cenaLeto;
    @XmlElement(required = true)
    protected BigDecimal cenaJesen;
    @XmlElement(required = true)
    protected BigDecimal cenaZima;
    protected long vlasnik;
    @XmlList
    @XmlElement(required = true)
    protected List<DodatneUsluge> listaDodatnihUsluga;
    /*@XmlElement(required = true)
    protected Smestaj.ListaSlika listaSlika;*/
    
    public Smestaj() {

	}

    public Smestaj(long idSmestaja, String adresa, BigDecimal latitude, BigDecimal longitude, TipSmestaja tipSmestaja,
    		KategorijaSmestaja kategorijaSmestaja, String opis, int maxOsoba, int maxDanaZaOtkazivanje,
			BigDecimal cenaProlece, BigDecimal cenaLeto, BigDecimal cenaJesen, BigDecimal cenaZima, long vlasnik, List<DodatneUsluge> listaDodatnihUsluga) {
		super();
		this.idSmestaja = idSmestaja;
		this.adresa = adresa;
		this.latitude = latitude;
		this.longitude = longitude;
		this.tipSmestaja = tipSmestaja;
		this.kategorijaSmestaja = kategorijaSmestaja;
		this.opis = opis;
		this.maxOsoba = maxOsoba;
		this.maxDanaZaOtkazivanje = maxDanaZaOtkazivanje;
		this.cenaProlece = cenaProlece;
		this.cenaLeto = cenaLeto;
		this.cenaJesen = cenaJesen;
		this.cenaZima = cenaZima;
		this.vlasnik = vlasnik;
		this.listaDodatnihUsluga = listaDodatnihUsluga;
		//this.listaSlika = listaSlika;
	}

    /**
     * Gets the value of the idSmestaja property.
     * 
     */
    public long getIdSmestaja() {
        return idSmestaja;
    }

    /**
     * Sets the value of the idSmestaja property.
     * 
     */
    public void setIdSmestaja(long value) {
        this.idSmestaja = value;
    }

    /**
     * Gets the value of the adresa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdresa() {
        return adresa;
    }

    /**
     * Sets the value of the adresa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdresa(String value) {
        this.adresa = value;
    }

    /**
     * Gets the value of the koordinate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    

    /**
     * Gets the value of the tipSmestaja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */

    public BigDecimal getLatitude() {
		return latitude;
	}

	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	public BigDecimal getLongitude() {
		return longitude;
	}

	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}
	
    /*public Long getTip_id(){
        return tipSmestaja.getIdTipaSmestaja();
    }*/

	@JsonIgnore
	public TipSmestaja getTipSmestaja() {
		return tipSmestaja;
	}
	@JsonIgnore
	public void setTipSmestaja(TipSmestaja tipSmestaja) {
		this.tipSmestaja = tipSmestaja;
	}

	/**
     * Sets the value of the tipSmestaja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */

    /**
     * Gets the value of the kategorijaSmestaja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public KategorijaSmestaja getKategorijaSmestaja() {
        return kategorijaSmestaja;
    }

    /**
     * Sets the value of the kategorijaSmestaja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKategorijaSmestaja(KategorijaSmestaja value) {
        this.kategorijaSmestaja = value;
    }

    /**
     * Gets the value of the opis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpis() {
        return opis;
    }

    /**
     * Sets the value of the opis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpis(String value) {
        this.opis = value;
    }

    /**
     * Gets the value of the maxOsoba property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getMaxOsoba() {
        return maxOsoba;
    }

    /**
     * Sets the value of the maxOsoba property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setMaxOsoba(int value) {
        this.maxOsoba = value;
    }

    /**
     * Gets the value of the maxDanaZaOtkazivanje property.
     * 
     * @return
     *     possible object is
     *     {@link int }
     *     
     */
    public int getMaxDanaZaOtkazivanje() {
        return maxDanaZaOtkazivanje;
    }

    /**
     * Sets the value of the maxDanaZaOtkazivanje property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setMaxDanaZaOtkazivanje(int value) {
        this.maxDanaZaOtkazivanje = value;
    }

    /**
     * Gets the value of the cenaProlece property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCenaProlece() {
        return cenaProlece;
    }

    /**
     * Sets the value of the cenaProlece property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCenaProlece(BigDecimal value) {
        this.cenaProlece = value;
    }

    /**
     * Gets the value of the cenaLeto property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCenaLeto() {
        return cenaLeto;
    }

    /**
     * Sets the value of the cenaLeto property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCenaLeto(BigDecimal value) {
        this.cenaLeto = value;
    }

    /**
     * Gets the value of the cenaJesen property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCenaJesen() {
        return cenaJesen;
    }

    /**
     * Sets the value of the cenaJesen property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCenaJesen(BigDecimal value) {
        this.cenaJesen = value;
    }

    /**
     * Gets the value of the cenaZima property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCenaZima() {
        return cenaZima;
    }

    /**
     * Sets the value of the cenaZima property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCenaZima(BigDecimal value) {
        this.cenaZima = value;
    }

    /**
     * Gets the value of the vlasnik property.
     * 
     */
    public long getVlasnik() {
        return vlasnik;
    }

    /**
     * Sets the value of the vlasnik property.
     * 
     */
    public void setVlasnik(long value) {
        this.vlasnik = value;
    }

    /**
     * Gets the value of the listaDodatnihUsluga property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the listaDodatnihUsluga property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getListaDodatnihUsluga().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<DodatneUsluge> getListaDodatnihUsluga() {
        if (listaDodatnihUsluga == null) {
            listaDodatnihUsluga = new ArrayList<DodatneUsluge>();
        }
        return this.listaDodatnihUsluga;
    }
    
    public void setListaDodatnihUsluga(List<DodatneUsluge> listaDodatnihUsluga) {
		this.listaDodatnihUsluga = listaDodatnihUsluga;
	}

    /**
     * Gets the value of the listaSlika property.
     * 
     * @return
     *     possible object is
     *     {@link Smestaj.ListaSlika }
     *     
     */
    /*public Smestaj.ListaSlika getListaSlika() {
        return listaSlika;
    }*/

    /**
     * Sets the value of the listaSlika property.
     * 
     * @param value
     *     allowed object is
     *     {@link Smestaj.ListaSlika }
     *     
     */
    /*public void setListaSlika(Smestaj.ListaSlika value) {
        this.listaSlika = value;
    }*/


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="slika" type="{https://github.com/MarkoKatic96/megaTravel/xmlagent}TImage"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "slika"
    })
    public static class ListaSlika {

        @XmlElement(required = true)
        protected List<TImage> slika;

        /**
         * Gets the value of the slika property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the slika property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSlika().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TImage }
         * 
         * 
         */
        public List<TImage> getSlika() {
            if (slika == null) {
                slika = new ArrayList<TImage>();
            }
            return this.slika;
        }

    }

}
