//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.22 at 11:00:08 PM CEST 
//


package io.webxml.pretragaservice.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipSmestaja.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TipSmestaja">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="HOTELSKA_SOBA"/>
 *     &lt;enumeration value="APARTMAN"/>
 *     &lt;enumeration value="BED_AND_BREAKFAST"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TipSmestaja")
@XmlEnum
public enum TipSmestaja {

    HOTELSKA_SOBA,
    APARTMAN,
    BED_AND_BREAKFAST;

    public String value() {
        return name();
    }

    public static TipSmestaja fromValue(String v) {
        return valueOf(v);
    }

}
