version: '3'
services:

  discovery:
    image: discovery-server
    container_name: discovery-server
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    environment: 
      eureka.client.serviceUrl.defaultZone: http://discovery:8761/eureka
    ports:
      - "8761:8761"

  gateway:
    image: zuul-gateway
    container_name: zuul-gateway
    build:
      context: ./zuul-gateway
      dockerfile: Dockerfile
    environment: 
      eureka.client.serviceUrl.defaultZone: http://discovery:8761/eureka
    ports:
      - "8762:8762"
    depends_on:
      - discovery
    links:
      - discovery:discovery

  #db:
  #  image: mysql:latest
  #  container_name: db
  #  environment:
  #    - MYSQL_ROOT_PASSWORD=root
  #    - MYSQL_DATABASE=db_xml
  #    - MYSQL_USER=root
  #    - MYSQL_PASSWORD=root
  #  ports:
  #    - "3306:3306"
  #  healthcheck:
  #    test: "exit 0"

  admin-service:
    image: admin-service
    container_name: admin-service
    build:
      context: ./admin-service
      dockerfile: Dockerfile
    environment: 
      eureka.client.serviceUrl.defaultZone: http://discovery:8761/eureka
    ports:
      - "8000:8000"
    depends_on:
      - discovery
   #   - db      
    links:
      - discovery:discovery
   #   - db:db
   # environment: 
   #   - DATABASE_HOST=db
   #   - DATABASE_USER=root
   #   - DATABASE_PASSWORD=root
   #   - DATABASE_NAME=db_xml
   #   - DATABASE_PORT=3306
   # healthcheck:
   #   test: ["CMD-SHELL", 'mysqladmin ping']
   #   interval: 10s
   #   timeout: 2s
   #   retries: 10

  agent-global-service:
    image: agent-global-service
    container_name: agent-global-service
    build:
      context: ./agent-global-service
      dockerfile: Dockerfile
    environment: 
      eureka.client.serviceUrl.defaultZone: http://discovery:8761/eureka
    ports:
      - "8400:8400"
    depends_on:
      - discovery
    links:
      - discovery:discovery

  agent-local-service:
    image: agent-local-service
    container_name: agent-local-service
    build:
      context: ./agent-local-back
      dockerfile: Dockerfile
    environment: 
      eureka.client.serviceUrl.defaultZone: http://discovery:8761/eureka
    ports:
      - "8500:8500"
    depends_on:
      - discovery
    links:
      - discovery:discovery

  korisnik-service:
    image: korisnik-service
    container_name: korisnik-service
    build:
      context: ./korisnik-service
      dockerfile: Dockerfile
    environment: 
      eureka.client.serviceUrl.defaultZone: http://discovery:8761/eureka
    ports:
      - "8100:8100"
    depends_on:
      - discovery
    links:
      - discovery:discovery

  poruke-service:
    image: poruke-service
    container_name: poruke-service
    build:
      context: ./poruke-service
      dockerfile: Dockerfile
    environment: 
      eureka.client.serviceUrl.defaultZone: http://discovery:8761/eureka
    ports:
      - "8700:8700"
    depends_on:
      - discovery
    links:
      - discovery:discovery

  pretraga-service:
    image: pretraga-service
    container_name: pretraga-service
    build:
      context: ./pretraga-service
      dockerfile: Dockerfile
    environment: 
      eureka.client.serviceUrl.defaultZone: http://discovery:8761/eureka
    ports:
      - "8200:8200"
    depends_on:
      - discovery
    links:
      - discovery:discovery

  rating-service:
    image: rating-service
    container_name: rating-service
    build:
      context: ./rating-service
      dockerfile: Dockerfile
    environment: 
      eureka.client.serviceUrl.defaultZone: http://discovery:8761/eureka
    ports:
      - "8900:8900"
    depends_on:
      - discovery
    links:
      - discovery:discovery

  reservation-service:
    image: reservation-service
    container_name: reservation-service
    build:
      context: ./reservation-service
      dockerfile: Dockerfile
    environment: 
      eureka.client.serviceUrl.defaultZone: http://discovery:8761/eureka
    ports:
      - "8300:8300"
    depends_on:
      - discovery
    links:
      - discovery:discovery

  
  smestaj-service:
    image: smestaj-service
    container_name: smestaj-service
    build:
      context: ./smestaj-service
      dockerfile: Dockerfile
    environment: 
      eureka.client.serviceUrl.defaultZone: http://discovery:8761/eureka
    ports:
      - "8600:8600"
    depends_on:
      - discovery
    links:
      - discovery:discovery
