//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 12:36:07 PM CEST 
//


package com.megatravel.agentlocalbackend.wsdl;

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="potvrdaRezervacijeId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="rezervacijaId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="statusRezervacije" type="{https://megatravel.com}statusRezervacije"/&gt;
 *         &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "potvrdaRezervacijeId",
    "rezervacijaId",
    "statusRezervacije",
    "timestamp"
})
@XmlRootElement(name = "PotvrdaRezervacije")
public class PotvrdaRezervacije {

    protected long potvrdaRezervacijeId;
    protected long rezervacijaId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected StatusRezervacije statusRezervacije;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected Date timestamp;

    /**
     * Gets the value of the potvrdaRezervacijeId property.
     * 
     */
    public long getPotvrdaRezervacijeId() {
        return potvrdaRezervacijeId;
    }

    /**
     * Sets the value of the potvrdaRezervacijeId property.
     * 
     */
    public void setPotvrdaRezervacijeId(long value) {
        this.potvrdaRezervacijeId = value;
    }

    /**
     * Gets the value of the rezervacijaId property.
     * 
     */
    public long getRezervacijaId() {
        return rezervacijaId;
    }

    /**
     * Sets the value of the rezervacijaId property.
     * 
     */
    public void setRezervacijaId(long value) {
        this.rezervacijaId = value;
    }

    /**
     * Gets the value of the statusRezervacije property.
     * 
     * @return
     *     possible object is
     *     {@link StatusRezervacije }
     *     
     */
    public StatusRezervacije getStatusRezervacije() {
        return statusRezervacije;
    }

    /**
     * Sets the value of the statusRezervacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusRezervacije }
     *     
     */
    public void setStatusRezervacije(StatusRezervacije value) {
        this.statusRezervacije = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setTimestamp(Date value) {
        this.timestamp = value;
    }

}
