//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.16 at 08:55:09 PM CEST 
//


package com.megatravel.agentglobalback.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlType;

@XmlType(name = "DodatneUsluge")
//@XmlEnum
@Entity
public class DodatneUsluge {
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	
	@NotNull
	private String dodatnaUsluga;
	
	@ManyToOne
	private Smestaj smestaj;

	public DodatneUsluge(Long id, @NotNull String dodatnaUsluga) {
		super();
		this.id = id;
		this.dodatnaUsluga = dodatnaUsluga;
	}
	
	public DodatneUsluge() {
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getDodatnaUsluga() {
		return dodatnaUsluga;
	}

	public void setDodatnaUsluga(String dodatnaUsluga) {
		this.dodatnaUsluga = dodatnaUsluga;
	}
	
	
	
	/*
    @XmlEnumValue("Parking")
    PARKING("Parking"),
    @XmlEnumValue("WiFi")
    WI_FI("WiFi"),
    @XmlEnumValue("Dorucak")
    DORUCAK("Dorucak"),
    @XmlEnumValue("Polupansion")
    POLUPANSION("Polupansion"),
    @XmlEnumValue("Pansion")
    PANSION("Pansion"),
    @XmlEnumValue("AllIncluded")
    ALL_INCLUDED("AllIncluded"),
    @XmlEnumValue("DozvoljeniKucniLjubimci")
    DOZVOLJENI_KUCNI_LJUBIMCI("DozvoljeniKucniLjubimci"),
    TV("TV"),
    @XmlEnumValue("MiniKuhinjaIliKuhinja")
    MINI_KUHINJA_ILI_KUHINJA("MiniKuhinjaIliKuhinja"),
    @XmlEnumValue("PrivatnoKupatilo")
    PRIVATNO_KUPATILO("PrivatnoKupatilo"),
    @XmlEnumValue("BesplatnoOtkazivanje")
    BESPLATNO_OTKAZIVANJE("BesplatnoOtkazivanje");
    
    private final String value;

    DodatneUsluge(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DodatneUsluge fromValue(String v) {
        for (DodatneUsluge c: DodatneUsluge.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	*/
	
	
}
