//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.16 at 08:55:09 PM CEST 
//


package com.megatravel.agentglobalback.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlType;


@XmlType(name = "TipSmestaja")
//@XmlEnum
@Entity
public class TipSmestaja {
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	
	@NotNull
	private String tipSmestaja;
	
	@OneToOne
	private Smestaj smestaj;

	public TipSmestaja(Long id, @NotNull String tipSmestaja, Smestaj smestaj) {
		super();
		this.id = id;
		this.tipSmestaja = tipSmestaja;
		this.smestaj = smestaj;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getTipSmestaja() {
		return tipSmestaja;
	}

	public void setTipSmestaja(String tipSmestaja) {
		this.tipSmestaja = tipSmestaja;
	}

	public Smestaj getSmestaj() {
		return smestaj;
	}

	public void setSmestaj(Smestaj smestaj) {
		this.smestaj = smestaj;
	}
	
	
	/*
    HOTELSKA_SOBA,
    APARTMAN,
    BED_AND_BREAKFAST;

    public String value() {
        return name();
    }

    public static TipSmestaja fromValue(String v) {
        return valueOf(v);
    }
	*/
}
