//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.22 at 11:00:08 PM CEST 
//


package io.xws.adminservice.model;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idKomentara",
    "idSmestaja",
    "idRezervacije",
    "idKorisnika",
    "komentar",
    "datum"
})
@XmlRootElement(name = "Komentar")
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Komentar {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
    protected long idKomentara;
    protected long idSmestaja;
    protected long idRezervacije;
    protected long idKorisnika;
    @XmlElement(required = true)
    protected String komentar;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected Date datum;
    protected boolean objavljen;

}
