//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.22 at 11:00:08 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://github.com/MarkoKatic96/megaTravel/xmlagent", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package io.xws.adminservice.model;
