//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.22 at 11:00:08 PM CEST 
//


package io.xws.adminservice.model;


import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idSmestaja",
    "adresa",
    "longitude",
    "latitude",
    "tipSmestaja",
    "kategorijaSmestaja",
    "opis",
    "maxOsoba",
    "maxDanaZaOtkazivanje",
    "cenaProlece",
    "cenaLeto",
    "cenaJesen",
    "cenaZima",
    "vlasnik",
    "listaDodatnihUsluga",
    "listaSlika"
})
@XmlRootElement(name = "Smestaj")
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Smestaj {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
    protected long idSmestaja;
    
    @XmlElement(required = true)
    protected String adresa;
    
    @XmlElement(required = true)
    protected float longitude;
    
    @XmlElement(required = true)
    protected float latitude;
    
    //vrati na tip smestaja (trebace neka veza many to one
    @XmlElement(required = true)
    @ManyToOne
    @JoinColumn(name="tipsmestaja_id", nullable = false)
    protected TipSmestaja tipSmestaja;
    
    @ManyToOne
    @JoinColumn(name="kategorijasmestaja_id", nullable = false)
    protected KategorijaSmestaja kategorijaSmestaja;
    
//    @XmlElement(required = true, defaultValue = "no star")
//    protected String kategorijaSmestaja;
    
    @XmlElement(required = true)
    protected String opis;
    
    @XmlElement(required = true)
    protected BigInteger maxOsoba;
    
    @XmlElement(required = true)
    protected BigInteger maxDanaZaOtkazivanje;
    
    @XmlElement(required = true)
    protected BigDecimal cenaProlece;
    
    @XmlElement(required = true)
    protected BigDecimal cenaLeto;
    
    @XmlElement(required = true)
    protected BigDecimal cenaJesen;
    
    @XmlElement(required = true)
    protected BigDecimal cenaZima;
    
    protected long vlasnik;
    @XmlList 
    @XmlElement(required = true)
    @ManyToMany
    @JoinTable(name = "smestaj_usluge", 
    				joinColumns = @JoinColumn(name="smestaj_id"),
    				inverseJoinColumns = @JoinColumn(name="tipsmestaja_id"))
    protected List<DodatneUsluge> listaDodatnihUsluga;
//    
//    @XmlElement(required = true)
//    protected Smestaj.ListaSlika listaSlika;

    
    
    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="slika" type="{https://github.com/MarkoKatic96/megaTravel/xmlagent}TImage"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "slika"
    })
    public static class ListaSlika {

        @XmlElement(required = true)
        protected List<TImage> slika;

        /**
         * Gets the value of the slika property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the slika property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSlika().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TImage }
         * 
         * 
         */
        public List<TImage> getSlika() {
            if (slika == null) {
                slika = new ArrayList<TImage>();
            }
            return this.slika;
        }

    }

}
