//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 12:36:07 PM CEST 
//


package com.megatravel.agentlocalbackend.wsdl;

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="agent"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="idAgenta" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *                   &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="poslovniMaticniBroj" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *                   &lt;element name="datumClanstva" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                   &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="lozinka" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "agent"
})
@XmlRootElement(name = "getAgentByEmailResponse")
public class GetAgentByEmailResponse {

    @XmlElement(required = true)
    protected GetAgentByEmailResponse.Agent agent;

    /**
     * Gets the value of the agent property.
     * 
     * @return
     *     possible object is
     *     {@link GetAgentByEmailResponse.Agent }
     *     
     */
    public GetAgentByEmailResponse.Agent getAgent() {
        return agent;
    }

    /**
     * Sets the value of the agent property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetAgentByEmailResponse.Agent }
     *     
     */
    public void setAgent(GetAgentByEmailResponse.Agent value) {
        this.agent = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="idAgenta" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
     *         &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="poslovniMaticniBroj" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
     *         &lt;element name="datumClanstva" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="lozinka" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "idAgenta",
        "ime",
        "prezime",
        "poslovniMaticniBroj",
        "datumClanstva",
        "email",
        "lozinka"
    })
    public static class Agent {

        protected long idAgenta;
        @XmlElement(required = true)
        protected String ime;
        @XmlElement(required = true)
        protected String prezime;
        protected Long poslovniMaticniBroj;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected Date datumClanstva;
        @XmlElement(required = true)
        protected String email;
        @XmlElement(required = true)
        protected String lozinka;

        /**
         * Gets the value of the idAgenta property.
         * 
         */
        public long getIdAgenta() {
            return idAgenta;
        }

        /**
         * Sets the value of the idAgenta property.
         * 
         */
        public void setIdAgenta(long value) {
            this.idAgenta = value;
        }

        /**
         * Gets the value of the ime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIme() {
            return ime;
        }

        /**
         * Sets the value of the ime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIme(String value) {
            this.ime = value;
        }

        /**
         * Gets the value of the prezime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrezime() {
            return prezime;
        }

        /**
         * Sets the value of the prezime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrezime(String value) {
            this.prezime = value;
        }

        /**
         * Gets the value of the poslovniMaticniBroj property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getPoslovniMaticniBroj() {
            return poslovniMaticniBroj;
        }

        /**
         * Sets the value of the poslovniMaticniBroj property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setPoslovniMaticniBroj(Long value) {
            this.poslovniMaticniBroj = value;
        }

        /**
         * Gets the value of the datumClanstva property.
         * 
         * @return
         *     possible object is
         *     {@link Date }
         *     
         */
        public Date getDatumClanstva() {
            return datumClanstva;
        }

        /**
         * Sets the value of the datumClanstva property.
         * 
         * @param value
         *     allowed object is
         *     {@link Date }
         *     
         */
        public void setDatumClanstva(Date value) {
            this.datumClanstva = value;
        }

        /**
         * Gets the value of the email property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmail() {
            return email;
        }

        /**
         * Sets the value of the email property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmail(String value) {
            this.email = value;
        }

        /**
         * Gets the value of the lozinka property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLozinka() {
            return lozinka;
        }

        /**
         * Sets the value of the lozinka property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLozinka(String value) {
            this.lozinka = value;
        }

    }

}
