//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 12:36:07 PM CEST 
//


package com.megatravel.agentlocalbackend.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.megatravel.agentlocalbackend.wsdl.cpy package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Agent_QNAME = new QName("https://megatravel.com", "Agent");
    private final static QName _DodatneUsluge_QNAME = new QName("https://megatravel.com", "DodatneUsluge");
    private final static QName _KategorijaSmestaja_QNAME = new QName("https://megatravel.com", "KategorijaSmestaja");
    private final static QName _Poruka_QNAME = new QName("https://megatravel.com", "Poruka");
    private final static QName _TImage_QNAME = new QName("https://megatravel.com", "TImage");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.megatravel.agentlocalbackend.wsdl.cpy
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link com.megatravel.agentlocalbackend.wsdl.Smestaj }
     * 
     */
    public com.megatravel.agentlocalbackend.wsdl.Smestaj createSmestaj() {
        return new com.megatravel.agentlocalbackend.wsdl.Smestaj();
    }

    /**
     * Create an instance of {@link GetAgentByEmailResponse }
     * 
     */
    public GetAgentByEmailResponse createGetAgentByEmailResponse() {
        return new GetAgentByEmailResponse();
    }

    /**
     * Create an instance of {@link SignUpResponse }
     * 
     */
    public SignUpResponse createSignUpResponse() {
        return new SignUpResponse();
    }

    /**
     * Create an instance of {@link SmestajDTO }
     * 
     */
    public SmestajDTO createSmestajDTO() {
        return new SmestajDTO();
    }

    /**
     * Create an instance of {@link SmestajDTO.ListaSlika }
     * 
     */
    public SmestajDTO.ListaSlika createSmestajDTOListaSlika() {
        return new SmestajDTO.ListaSlika();
    }

    /**
     * Create an instance of {@link DodatneUsluge }
     * 
     */
    public DodatneUsluge createDodatneUsluge() {
        return new DodatneUsluge();
    }

    /**
     * Create an instance of {@link KategorijaSmestaja }
     * 
     */
    public KategorijaSmestaja createKategorijaSmestaja() {
        return new KategorijaSmestaja();
    }

    /**
     * Create an instance of {@link Poruka }
     * 
     */
    public Poruka createPoruka() {
        return new Poruka();
    }

    /**
     * Create an instance of {@link PotvrdaRezervacije }
     * 
     */
    public PotvrdaRezervacije createPotvrdaRezervacije() {
        return new PotvrdaRezervacije();
    }

    /**
     * Create an instance of {@link RevokedTokens }
     * 
     */
    public RevokedTokens createRevokedTokens() {
        return new RevokedTokens();
    }

    /**
     * Create an instance of {@link Rezervacija }
     * 
     */
    public Rezervacija createRezervacija() {
        return new Rezervacija();
    }

    /**
     * Create an instance of {@link SamostalnaRezervacija }
     * 
     */
    public SamostalnaRezervacija createSamostalnaRezervacija() {
        return new SamostalnaRezervacija();
    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link TipSmestaja }
     * 
     */
    public TipSmestaja createTipSmestaja() {
        return new TipSmestaja();
    }

    /**
     * Create an instance of {@link com.megatravel.agentlocalbackend.wsdl.Smestaj.ListaSlika }
     * 
     */
    public com.megatravel.agentlocalbackend.wsdl.Smestaj.ListaSlika createSmestajListaSlika() {
        return new com.megatravel.agentlocalbackend.wsdl.Smestaj.ListaSlika();
    }

    /**
     * Create an instance of {@link GetAgentByEmailRequest }
     * 
     */
    public GetAgentByEmailRequest createGetAgentByEmailRequest() {
        return new GetAgentByEmailRequest();
    }

    /**
     * Create an instance of {@link GetAgentByEmailResponse.Agent }
     * 
     */
    public GetAgentByEmailResponse.Agent createGetAgentByEmailResponseAgent() {
        return new GetAgentByEmailResponse.Agent();
    }

    /**
     * Create an instance of {@link GetAgentRequest }
     * 
     */
    public GetAgentRequest createGetAgentRequest() {
        return new GetAgentRequest();
    }

    /**
     * Create an instance of {@link GetAgentResponse }
     * 
     */
    public GetAgentResponse createGetAgentResponse() {
        return new GetAgentResponse();
    }

    /**
     * Create an instance of {@link AgentDTO }
     * 
     */
    public AgentDTO createAgentDTO() {
        return new AgentDTO();
    }

    /**
     * Create an instance of {@link LoginRequest }
     * 
     */
    public LoginRequest createLoginRequest() {
        return new LoginRequest();
    }

    /**
     * Create an instance of {@link AgentPrijavaDTO }
     * 
     */
    public AgentPrijavaDTO createAgentPrijavaDTO() {
        return new AgentPrijavaDTO();
    }

    /**
     * Create an instance of {@link LoginResponse }
     * 
     */
    public LoginResponse createLoginResponse() {
        return new LoginResponse();
    }

    /**
     * Create an instance of {@link SignUpRequest }
     * 
     */
    public SignUpRequest createSignUpRequest() {
        return new SignUpRequest();
    }

    /**
     * Create an instance of {@link AgentRegistracijaDTO }
     * 
     */
    public AgentRegistracijaDTO createAgentRegistracijaDTO() {
        return new AgentRegistracijaDTO();
    }

    /**
     * Create an instance of {@link SignUpResponse.NeaktiviranAgent }
     * 
     */
    public SignUpResponse.NeaktiviranAgent createSignUpResponseNeaktiviranAgent() {
        return new SignUpResponse.NeaktiviranAgent();
    }

    /**
     * Create an instance of {@link ValidateTokenRequest }
     * 
     */
    public ValidateTokenRequest createValidateTokenRequest() {
        return new ValidateTokenRequest();
    }

    /**
     * Create an instance of {@link ValidateTokenResponse }
     * 
     */
    public ValidateTokenResponse createValidateTokenResponse() {
        return new ValidateTokenResponse();
    }

    /**
     * Create an instance of {@link GetLoginResponse }
     * 
     */
    public GetLoginResponse createGetLoginResponse() {
        return new GetLoginResponse();
    }

    /**
     * Create an instance of {@link GetLoginRequest }
     * 
     */
    public GetLoginRequest createGetLoginRequest() {
        return new GetLoginRequest();
    }

    /**
     * Create an instance of {@link TKoordinate }
     * 
     */
    public TKoordinate createTKoordinate() {
        return new TKoordinate();
    }

    /**
     * Create an instance of {@link RezervacijaDTO }
     * 
     */
    public RezervacijaDTO createRezervacijaDTO() {
        return new RezervacijaDTO();
    }

    /**
     * Create an instance of {@link PorukaDTO }
     * 
     */
    public PorukaDTO createPorukaDTO() {
        return new PorukaDTO();
    }

    /**
     * Create an instance of {@link LokalneRezervacijeDTO }
     * 
     */
    public LokalneRezervacijeDTO createLokalneRezervacijeDTO() {
        return new LokalneRezervacijeDTO();
    }

    /**
     * Create an instance of {@link NovaPorukaDTO }
     * 
     */
    public NovaPorukaDTO createNovaPorukaDTO() {
        return new NovaPorukaDTO();
    }

    /**
     * Create an instance of {@link SamostalnaRezervacijaDTO }
     * 
     */
    public SamostalnaRezervacijaDTO createSamostalnaRezervacijaDTO() {
        return new SamostalnaRezervacijaDTO();
    }

    /**
     * Create an instance of {@link SmestajDTO.ListaSlika.Smestaj }
     * 
     */
    public SmestajDTO.ListaSlika.Smestaj createSmestajDTOListaSlikaSmestaj() {
        return new SmestajDTO.ListaSlika.Smestaj();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://megatravel.com", name = "Agent")
    public JAXBElement<Object> createAgent(Object value) {
        return new JAXBElement<Object>(_Agent_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DodatneUsluge }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://megatravel.com", name = "DodatneUsluge")
    public JAXBElement<DodatneUsluge> createDodatneUsluge(DodatneUsluge value) {
        return new JAXBElement<DodatneUsluge>(_DodatneUsluge_QNAME, DodatneUsluge.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KategorijaSmestaja }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://megatravel.com", name = "KategorijaSmestaja")
    public JAXBElement<KategorijaSmestaja> createKategorijaSmestaja(KategorijaSmestaja value) {
        return new JAXBElement<KategorijaSmestaja>(_KategorijaSmestaja_QNAME, KategorijaSmestaja.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Poruka }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://megatravel.com", name = "Poruka")
    public JAXBElement<Poruka> createPoruka(Poruka value) {
        return new JAXBElement<Poruka>(_Poruka_QNAME, Poruka.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://megatravel.com", name = "TImage")
    public JAXBElement<Object> createTImage(Object value) {
        return new JAXBElement<Object>(_TImage_QNAME, Object.class, null, value);
    }

}
