//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 12:36:07 PM CEST 
//


package com.megatravel.agentlocalbackend.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for rezervacijaDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rezervacijaDTO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="doDatuma" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="korisnikId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="odDatuma" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="rezervacijaId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="smestajId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="statusRezervacije" type="{https://megatravel.com}statusRezervacije" minOccurs="0"/&gt;
 *         &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="updateTimestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="vlasnikId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rezervacijaDTO", propOrder = {
    "doDatuma",
    "korisnikId",
    "odDatuma",
    "rezervacijaId",
    "smestajId",
    "statusRezervacije",
    "timestamp",
    "updateTimestamp",
    "vlasnikId"
})
public class RezervacijaDTO {

    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar doDatuma;
    protected Long korisnikId;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar odDatuma;
    protected Long rezervacijaId;
    protected Long smestajId;
    @XmlSchemaType(name = "string")
    protected StatusRezervacije statusRezervacije;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestamp;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar updateTimestamp;
    protected Long vlasnikId;

    /**
     * Gets the value of the doDatuma property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDoDatuma() {
        return doDatuma;
    }

    /**
     * Sets the value of the doDatuma property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDoDatuma(XMLGregorianCalendar value) {
        this.doDatuma = value;
    }

    /**
     * Gets the value of the korisnikId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getKorisnikId() {
        return korisnikId;
    }

    /**
     * Sets the value of the korisnikId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setKorisnikId(Long value) {
        this.korisnikId = value;
    }

    /**
     * Gets the value of the odDatuma property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOdDatuma() {
        return odDatuma;
    }

    /**
     * Sets the value of the odDatuma property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOdDatuma(XMLGregorianCalendar value) {
        this.odDatuma = value;
    }

    /**
     * Gets the value of the rezervacijaId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRezervacijaId() {
        return rezervacijaId;
    }

    /**
     * Sets the value of the rezervacijaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRezervacijaId(Long value) {
        this.rezervacijaId = value;
    }

    /**
     * Gets the value of the smestajId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSmestajId() {
        return smestajId;
    }

    /**
     * Sets the value of the smestajId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSmestajId(Long value) {
        this.smestajId = value;
    }

    /**
     * Gets the value of the statusRezervacije property.
     * 
     * @return
     *     possible object is
     *     {@link StatusRezervacije }
     *     
     */
    public StatusRezervacije getStatusRezervacije() {
        return statusRezervacije;
    }

    /**
     * Sets the value of the statusRezervacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusRezervacije }
     *     
     */
    public void setStatusRezervacije(StatusRezervacije value) {
        this.statusRezervacije = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the updateTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * Sets the value of the updateTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdateTimestamp(XMLGregorianCalendar value) {
        this.updateTimestamp = value;
    }

    /**
     * Gets the value of the vlasnikId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVlasnikId() {
        return vlasnikId;
    }

    /**
     * Sets the value of the vlasnikId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVlasnikId(Long value) {
        this.vlasnikId = value;
    }

}
