//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 12:36:07 PM CEST 
//


package com.megatravel.agentlocalbackend.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="neaktiviranAgent"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="idNeaktiviranogAgenta" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *                   &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="poslovniMaticniBroj" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *                   &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "neaktiviranAgent"
})
@XmlRootElement(name = "signUpResponse")
public class SignUpResponse {

    @XmlElement(required = true)
    protected SignUpResponse.NeaktiviranAgent neaktiviranAgent;

    /**
     * Gets the value of the neaktiviranAgent property.
     * 
     * @return
     *     possible object is
     *     {@link SignUpResponse.NeaktiviranAgent }
     *     
     */
    public SignUpResponse.NeaktiviranAgent getNeaktiviranAgent() {
        return neaktiviranAgent;
    }

    /**
     * Sets the value of the neaktiviranAgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignUpResponse.NeaktiviranAgent }
     *     
     */
    public void setNeaktiviranAgent(SignUpResponse.NeaktiviranAgent value) {
        this.neaktiviranAgent = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="idNeaktiviranogAgenta" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
     *         &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="poslovniMaticniBroj" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
     *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "idNeaktiviranogAgenta",
        "ime",
        "prezime",
        "poslovniMaticniBroj",
        "email"
    })
    public static class NeaktiviranAgent {

        protected long idNeaktiviranogAgenta;
        @XmlElement(required = true)
        protected String ime;
        @XmlElement(required = true)
        protected String prezime;
        protected long poslovniMaticniBroj;
        @XmlElement(required = true)
        protected String email;

        /**
         * Gets the value of the idNeaktiviranogAgenta property.
         * 
         */
        public long getIdNeaktiviranogAgenta() {
            return idNeaktiviranogAgenta;
        }

        /**
         * Sets the value of the idNeaktiviranogAgenta property.
         * 
         */
        public void setIdNeaktiviranogAgenta(long value) {
            this.idNeaktiviranogAgenta = value;
        }

        /**
         * Gets the value of the ime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIme() {
            return ime;
        }

        /**
         * Sets the value of the ime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIme(String value) {
            this.ime = value;
        }

        /**
         * Gets the value of the prezime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrezime() {
            return prezime;
        }

        /**
         * Sets the value of the prezime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrezime(String value) {
            this.prezime = value;
        }

        /**
         * Gets the value of the poslovniMaticniBroj property.
         * 
         */
        public long getPoslovniMaticniBroj() {
            return poslovniMaticniBroj;
        }

        /**
         * Sets the value of the poslovniMaticniBroj property.
         * 
         */
        public void setPoslovniMaticniBroj(long value) {
            this.poslovniMaticniBroj = value;
        }

        /**
         * Gets the value of the email property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmail() {
            return email;
        }

        /**
         * Sets the value of the email property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmail(String value) {
            this.email = value;
        }

    }

}
