//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 12:36:07 PM CEST 
//


package com.megatravel.agentlocalbackend.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="agentRegistracijaDTO" type="{https://megatravel.com}agentRegistracijaDTO"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "agentRegistracijaDTO"
})
@XmlRootElement(name = "signUpRequest")
public class SignUpRequest {

    @XmlElement(required = true)
    protected AgentRegistracijaDTO agentRegistracijaDTO;

    /**
     * Gets the value of the agentRegistracijaDTO property.
     * 
     * @return
     *     possible object is
     *     {@link AgentRegistracijaDTO }
     *     
     */
    public AgentRegistracijaDTO getAgentRegistracijaDTO() {
        return agentRegistracijaDTO;
    }

    /**
     * Sets the value of the agentRegistracijaDTO property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgentRegistracijaDTO }
     *     
     */
    public void setAgentRegistracijaDTO(AgentRegistracijaDTO value) {
        this.agentRegistracijaDTO = value;
    }

}
